# Site
name: Trade, Borders, Logistics Etc
title: Trade, Borders, Logistics Etc - The Trade Duty Refund Blog
description: Unlock duty refund insights. Discover strategies to reduce merchant returns costs, navigate the complexities of duty reclaim, and improve cash flow!
logo: assets/images/logo.webp
favicon: assets/images/favicon.ico
# baseurl: /
google_analytics: G-EGJMGN0WP7
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  TDR:
    name: TDR
    display_name: TDR
    tag: TDR
    avatar: assets/images/authors/TDR.webp
    email: contact@tradedutyrefund.com
    web: https://tradedutyrefund.com
    twitter: https://linkedIn.com/wowthemesnet
    description: TDR Editors.
  mark-neville:
    name: Mark Neville
    display_name: Mark Neville
    tag: mark-neville
    avatar: assets/images/authors/Mark.webp
    email: mkneville@itctradelaw.com
    web: https://itctradelaw.com
    twitter: https://www.linkedin.com/in/mark-neville-a0016521/
    description: "Mark K. Neville, Jr., LL.M. (International Legal Studies), NYU, is Principal of International Trade Counsellors. He has considerable experience in the field of international trade and customs affairs and international commercial transactions. He has successfully advised numerous United States and foreign-based companies on strategic matters of planning, compliance and enhanced efficiencies."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: /category/:name/

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  html_to_native: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
